### ISSUE TITLE
Examples break on `@import` from external sources, such as node_modules folder

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/sassdoc-theme-herman#156]
- See the `docs-import` branch on [Accoutrement-Color](https://github.com/oddbird/accoutrement-color/pull/7).
- Run `gulp sassdoc` to compile the docs and see the errors.

Sample Error:
```
» [WARNING] Error compiling @example scss: 
File to import not found or unreadable: ../node_modules/mathsass/dist/math.
Parent style sheet: stdin
@import 'color';
@import '../node_modules/mathsass/dist/math';
$background: #333;
html {
  background: $background;
  color: contrast($background);
}
```

**Comment by jgerigmeyer** [comment]
The path to `node_modules` here is relative to where the `@example` is compiled by sassdoc, not relative to the scss file. It works on most of our projects because we use e.g. `~mathsass`, which webpack understands and we've built herman to understand as well. You can fix this by either using `@import '~mathsass/dist/math';` or `@import './node_modules/mathsass/dist/math';`.

We should document in Herman how to include external files from node_modules. I'd lean toward just documenting how `~` works instead of trying to make it work relative to the scss file where it's written.

**Comment by mirisuzanne** [comment]
Makes sense for npm modules. How does it work for importing other files in your Sass dir?

**Comment by jgerigmeyer** [comment]
That's what the Herman `includepaths` setting is for. Which reminds me... Another way to solve this would be to add `node_modules` to that option. For instance, right now accoutrement-color has `includepaths: ['sass']`. If we change that to `includepaths: ['sass', 'node_modules']`, then just doing `@import 'mathsass/dist/math';` will work. So that would be another way to tell people to import from `node_modules`, if `~` feels too magical. In the case of accoutrement-color (and other packages not using Webpack), that's probably better.

We _could_ automatically add `'node_modules'` to the `includepaths` array... but I'm not sure that's a good idea?

**Comment by mirisuzanne** [comment]
oh, that makes sense. thanks!

What are the dangers of adding node_modules by default?

**Comment by jgerigmeyer** [comment]
This doesn't really answer the question of how to handle relative paths in `@example` `@import`s. I think we should just warn you against doing that, as we don't have a good way to resolve the path relative to the file being parsed.

I guess the dangers would be potentially importing something incorrect from node_modules when you intended to import something from a local file? We could put it last and hope that node-sass resolves them in order? (I can't find the order documented, but we could test it...)

**Comment by jgerigmeyer** [comment]
It also feels like allowing people to add `node_modules` themselves is more explicit? Like, these are the places we'll look for your imports in examples.

**Comment by mirisuzanne** [comment]
I like adding import paths, and imports manually as long as we can do it globally - which I think we can. So, technically I could add mathsass as one of the Sass "includes" rather than calling it for individual examples. With documentation, I think we already have a good system here. Explicit, without being redundant.
