### ISSUE TITLE
Cannot make mixins work in simple scenario - support request?

### ISSUE THREAD

**Issue by chrisfromredfin** [oddbird/sassdoc-theme-herman#231]
I wonder if I'm misunderstanding how to set this up. But I've set up a very simple example that I found here: https://www.sitepoint.com/sass-reference/sassdoc/ -- this is the only thing in my style.scss

```
/// Helper mixin to size elements in a single line.
/// This mixin is essentially a short hand to define
/// both `width` and `height` simultaneously.
///
/// @group Mixins
/// @author Hugo Giraudel
///
/// @param {Length} $width - Element's width
/// @param {Length} $height [$width] - Element's height
/// @output `width` and `height`
///
/// @example scss - Sizing `.foo`
///   .foo {
///     @include size(100%, 3em);
///   }
@mixin size($width, $height: $width) {
  width: $width;
  height: $height;
}
```

When using native SassDoc this works fine. With Herman, I see 
```
» [WARNING] Error compiling @example scss:
no mixin named size

Backtrace:
	stdin:2
.foo {
  @include size(100%, 3em);
}
```

In a way, this makes sense because if it's trying to literally compile the `@example` code, the mixin isn't defined yet. 

On the other hand, I want to document the mixin I'm creating right with the mixin I'm creating. (I could put the mixin in a separate file, import it, then include the documentation below it, right?) 

I could just not include the @example - or is there a way to flag the example as "don't try to compile?" In that sense, I believe I'd get the SCSS example but not the CSS example, right? (I'm new to this, after seeing Miriam's tweet yesterday about the release, but am also very excited about it. It's been the simplest thing to setup for us and we've tried 2-3 others - and we're totally an agency with some mix of enterprise/non-enterprise clients.)

**Comment by mirisuzanne** [comment]
@chrisfromredfin Sass examples require [access to the sass being documented](http://oddbird.net/herman/docs/demo_examples.html#compiling-sass-scss). You can do that a few ways. In either case, you'll need to set `sass.includepaths` in your [Herman configuration](http://oddbird.net/herman/docs/CONFIGURATION.html#sass-includepaths). From there you can:

1. Set global imports with the `sass.includes` configuration. We often include our Sass utility files (variables, mixins, functions, etc) globally, since they have no output.

2. Import sass files directly in the example, relative to any set `includepaths`. That would mean adding `@import 'path/to/your-file';` in the example itself. This is a better approach if you only need access to this file in a limited number of places.

(We might be able to consider a feature to automatically import the file you are in currently - though I haven't thought through all the implications of that. Happy for your thoughts.)

Let me know if that makes sense!

**Comment by chrisfromredfin** [comment]
Yes, this makes perfect sense! None of the examples I saw had an `@import` in them, so it just never clicked. With this explanation, though, it's perfect. 

The real missing piece for me was that the `@example` itself needed to be given _everything_ required in order to compile--either explicitly (as in your option 2), or through the use of sass.includes (your option 1, which is what I ultimately went with). 

So, it seems to me, in retrospect, that my prototype was probably a bit oversimple. If I had gone with something a touch closer to real-world, it may have clicked at that time, as I usually have a util/* folder with _mixins, _functions, etc. All that to say I don't know that it's worth the effort to auto-import "self" or anything like that, as long as this concept is clear in the documentation, or with some examples. Perhaps I'll put up a "getting started with Herman" blog post which is more of a walkthrough/how-to. 

Thanks so much for your quick turnaround on this! It's working beautifully now. Really excited to integrate this into our next project.

**Comment by mirisuzanne** [comment]
@chrisfromredfin We'd love to link a getting-started post if you do one. Let us know. I'm also going to reopen this, and mark it as a documentation issue to look into. Glad you got it sorted out!

**Comment by mirisuzanne** [comment]
(If you feel like submitting to the docs, PRs are also welcome. Otherwise, I'll get to it in the next week or so.)
